name: Auto Run Code

# Hành động này sẽ tự động kích hoạt mỗi khi bạn push code lên nhánh main
on:
  push:
    branches: [ "main" ]

jobs:
  run-script:
    runs-on: ubuntu-latest # Máy chủ ảo của GitHub (chạy Linux)

    steps:
      # Bước 1: Copy code từ repo của bạn vào máy chủ ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt môi trường Python (Nếu dùng C# thì đổi thành setup-dotnet)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib

      - name: Run code with Input/Output
        run: |
          python main.py < input.txt > output.txt
          
          echo "=== KẾT QUẢ OUTPUT ==="
          cat output.txt
